#!/usr/bin/env bash

version=${1?"You didn't pick a version"}
filename="gh_${version}_linux_amd64.deb"
wget "https://github.com/cli/cli/releases/download/v${version}/${filename}"
sudo apt install "./$filename"
rm "$filename"
