directory: ~/Music/Library
ignore: beets/
library: ~/Music/.beets/library.db
statefile: ~/Music/.beets/state.pickle
plugins: lyrics
import:
  copy: no
lyrics:
  sources: lrclib genius tekstowo
  synced: yes
